package Modelo;
// Generated 10/04/2015 09:20:12 AM by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellidos;
     private Integer edad;

    public Alumnos() {
    }

    public Alumnos(String nombre, String apellidos, Integer edad) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


